sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t davcarvalho88/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true davcarvalho88/docker-react npm run test 
