sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t davcarvalho88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davcarvalho88/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-658309509687"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"


